#%RAML 1.0 Library
usage:
traits:
  departureLocation: !include /Libraries/common/traits/departureLocation-queryparms-trait.raml
  destinationLocation: !include /Libraries/common/traits/destinationLocation-queryParams-trait.raml