#%RAML 1.0 Library
usage:
traits:
  companyName: !include /Libraries/common/traits/companycode-queryParams-trait.raml
  departureLocation: !include /Libraries/common/traits/departureLocation-queryparms-trait.raml
  destinationLocation: !include /Libraries/common/traits/destinationLocation-queryParams-trait.raml
  requestTimeZone: !include /Libraries/common/traits/requestTimeZone-queryParam-trait.raml